version: "3.6"
services:
  node:
    build: .
    user: "node"
    working_dir: /home/node/app
    entrypoint: docker-entrypoint-watch.sh
    environment:
      - NODE_ENV=development
    volumes:
      - codebase-docker-sync:/home/node/app
    ports:
      - "5000:5000"

volumes:
  codebase-docker-sync:
    external: true
