site_name: Plutus Community Docs
repo_url: https://github.com/plutus-community/docs/
theme: 
  name: windmill # cleaner for nested content and supporting more than 2 levels of depth
  #name: rtd-dropdown
  #name: readthedocs
  collapse_navigation: true
  sticky_navigation: false
  navigation_depth: 4
  includehidden: true
  titles_only: false
  features:
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list # For using e.g. [](){:target="_blank"}:
nav:
  - Environment Setup:
    - Build instructions:
      #- 'Getting Started': 'Environment/index.md'
      - 'Ubuntu': 'Environment/Build/Ubuntu.md'
      - 'Ubuntu (Fresh Install)': 'Environment/Build/Ubuntufresh.md'
      - 'Arch Linux': 'Environment/Build/ArchLinux.md'  
      - 'MacOS': 'Environment/Build/MacOS.md'  
      - 'MacOS M1': 'Environment/Build/Mac_M1.md'
      - 'Windows/WSL2 (2nd alternative)': 'Environment/Build/WindowsWSL.md'
      - 'NixOS (using Vagrant)': 'Environment/Build/Vagrant-Nixos.md'
    - Editors:
      - 'Prerequisites': 'Environment/Editors/Prerequisites/prerequisites.md'
      - 'Emacs': 'Environment/Editors/emacs.md'
      - 'Vim': 'Environment/Editors/vim.md'
      - 'VS Code': 'Environment/Editors/vscode.md'
      - 'Sublime Text': 'Environment/Editors/sublime_text.md'
      - 'intelliJ IDEA Windows': 'Environment/Editors/intelliJ-Windows.md'
    - Deprecated:
      - 'Docker': 'Outdated_Material/DockerCompose(needs_update).md'
      - 'Ubuntu (using Vagrant)': 'Outdated_Material/Vagrant-Ubuntu(needs_update).md'
      - 'Windows/WSL2 (1st alternative)': 'Outdated_Material/WindowsCohort2(needs_update).md'
  - Lectures:
    - Cohort 01:
      - 'Lectures': 'Lectures/Cohort_01/1st_Cohort.md'
      - '1. EUTxO and English Auction': 'Lectures/Cohort_01/Lecture_01.md'
      - '2. Validation Scripts': 'Lectures/Cohort_01/Lecture_02.md'
      - '3. Vesting': 'Lectures/Cohort_01/Lecture_03.md'
      - '4. Emulator Trace and Contract Monads': 'Lectures/Cohort_01/Lecture_04.md'
      - '5. Minting Policy': 'Lectures/Cohort_01/Lecture_05.md'
      - '6. Oracles': 'Lectures/Cohort_01/Lecture_06.md'
    - Cohort 02:
      - 'Lectures': 'Lectures/Cohort_02/2nd_Cohort.md'
      - '1. EUTxO and English Auction': 'Lectures/Cohort_02/Lecture_01.md'
      - '2. Validation Scripts': 'Lectures/Cohort_02/Lecture_02.md'
      - '3. Vesting': 'Lectures/Cohort_02/Lecture_03.md'
      - '4. Emulator Trace and Contract Monads': 'Lectures/Cohort_02/Lecture_04.md'
      - '5. Minting Policy': 'Lectures/Cohort_02/Lecture_05.md'
      - '6. Oracles': 'Lectures/Cohort_02/Lecture_06.md'
      - '7. State Machines': 'Lectures/Cohort_02/Lecture_07.md'
      - '8. Property Based Testing': 'Lectures/Cohort_02/Lecture_08.md'
      - '9. Marlowe': 'Lectures/Cohort_02/Lecture_07.md'
      - '10. Uniswap': 'Lectures/Cohort_02/Lecture_08.md'
    - Cohort 03:
      - 'Lectures': 'Lectures/Cohort_03/3rd_Cohort.md'
      - '1. EUTxO and English Auction': 'Lectures/Cohort_03/Lecture_01.md'
      - '2. Validation Scripts': 'Lectures/Cohort_03/Lecture_02.md'
      - '3. Vesting and Cardano Testnet': 'Lectures/Cohort_03/Lecture_03.md'
      - '4. Emulator Trace and Contract Monads': 'Lectures/Cohort_03/Lecture_04.md'
      - '5. Minting Policy': 'Lectures/Cohort_03/Lecture_05.md'
      - '6. Minting with CLI and PAB': 'Lectures/Cohort_03/Lecture_06.md'
      - '7. State Machines': 'Lectures/Cohort_03/Lecture_07.md'
      - '8. Property Based Testing': 'Lectures/Cohort_03/Lecture_08.md'
    - Translations:
      - 'French Cohort 3': 'Lectures/Translations/FR/Lectures/Cohort_03/FR_3rd_Cohort.md'  
  - Guides:
    - 'Using Plutus API Documentation': 'Environment/Guides/APIbuildDocumentation.md'
    - 'Using Plutus Playground for Plutus Pioneer Program': 'Environment/Guides/plutusplayground.md'
    - 'Using nix-shell for Plutus Pioneer Program': 'Environment/Guides/BuildCabalBuild.md'
    - 'Using PAB for Plutus Pioneer Program': 'Environment/Guides/PAB.md'
    - 'Syncing cardano-node for Plutus Pioneer Program': 'Environment/Guides/cnodesync.md'
  - Related Projects:
    - 'DEX': 'Open_Source_Cardano_Projects/DEX/Minswap.md'
    - 'NFTs': 'Open_Source_Cardano_Projects/NFTS/index_nfts.md'
    - 'Utility': 'Open_Source_Cardano_Projects/Utility/index_utility.md'
    - 'Wallets': 'Open_Source_Cardano_Projects/Wallets/Nami_Wallet.md'
  - 'About': 'README.md'
