site_name: Plutus Community Docs
repo_url: https://github.com/plutus-community/docs/
theme: 
  name: windmill # cleaner for nested content and supporting more than 2 levels of depth
  #name: rtd-dropdown
  #name: readthedocs
  collapse_navigation: true
  sticky_navigation: false
  navigation_depth: 4
  includehidden: true
  titles_only: false
  features:
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list # For using e.g. [](){:target="_blank"}:
nav:
  - Environment Setup:
    - Build:
      - 'Getting Started': 'Environment/index.md'
      - 'Ubuntu': 'Environment/Build/Ubuntu.md'
      - 'Ubuntu (Fresh Install)': 'Environment/Build/Ubuntufresh.md'
      - 'Arch Linux': 'Environment/Build/ArchLinux.md'  
      - 'MacOS': 'Environment/Build/MacOS.md'  
      - 'MacOS M1': 'Environment/Build/Mac_M1.md'
      - 'Windows/WSL2 (2nd alternative)': 'Environment/Build/WindowsWSL.md'
      - 'NixOS (using Vagrant)': 'Environment/Build/Vagrant-Nixos.md'
    - Editors:
      - 'Prerequisites': 'Environment/Editors/Prerequisites/prerequisites.md'
      - 'Emacs': 'Environment/Editors/emacs.md'
      - 'Vim': 'Environment/Editors/vim.md'
      - 'VS Code': 'Environment/Editors/vscode.md'
      - 'Sublime Text': 'Environment/Editors/sublime_text.md'
      - 'intelliJ IDEA Windows': 'Environment/Editors/intelliJ-Windows.md'
    - Deprecated:
      - 'Docker': 'Environment/Build/DockerCompose.md'
      - 'Ubuntu (using Vagrant)': 'Environment/Build/Vagrant-Ubuntu.md'
      - 'Windows/WSL2 (1st alternative)': 'Environment/Build/WindowsCohort2.md'
  - Lectures:
    - Cohort 01:
      - 'Lectures': 'Lectures/Cohort_01/1st_Cohort.md'
      - 'Lecture 01': 'Lectures/Cohort_01/Lecture_01.md'
    - Cohort 02:
      - 'Lectures': 'Lectures/Cohort_02/2nd_Cohort.md'
    - Cohort 03:
      - '1. EUTxO and English Auction': 'Lectures/Cohort_03/Lecture_01.md'
      - '2. Validation Scripts': 'Lectures/Cohort_03/Lecture_02.md'
      - '3. Vesting and Cardano Testnet': 'Lectures/Cohort_03/Lecture_03.md'
      - '4. Emulator Trace and Contract Monads': 'Lectures/Cohort_03/Lecture_04.md'
      - '5. Minting Policy': 'Lectures/Cohort_03/Lecture_05.md'
      - '6. Minting with CLI and PAB': 'Lectures/Cohort_03/Lecture_06.md'
      - '7. State Machines': 'Lectures/Cohort_03/Lecture_07.md'
      - '8. Property Based Testing': 'Lectures/Cohort_03/Lecture_08.md'
  - 'About': 'README.md'
    
 
#  - How Tos:
#    - Use Plutus API Documentation: Environment/Guides/APIbuildDocumentation.md
#    - Use nix-shell for Plutus Pioneer Program: Environment/Guides/BuildCabalBuild.md
#    - Use PAB for Plutus Pioneer Program: Environment/Guides/PAB.md
#    - Sync Cardano node for Plutus Pioneer Program: Environment/Guides/cnodesync.md
#    - Use Plutus Playground for Plutus Pioneer Program: Environment/Guides/plutusplayground.md
# "Working on contracts with and without cabal build"
#    - For every new lecture: Environment/Build/CabalBuild.md
# "Plutus API documentation"
#    - Environment/Build/buildDocumentation.md


#  - Open Source Cardano Projects:
#    - DEX: Open_Source_Cardano_Projects/DEX/Minswap.md
#    - NFTs: Open_Source_Cardano_Projects/NFTS/index_nfts.md
#    - Utility: Open_Source_Cardano_Projects/Utility/index_utility.md
#    - Wallets: Open_Source_Cardano_Projects/Wallets/Nami_Wallet.md

#  - Translations:
#    - French Cohort 3: Lectures/Translations/FR/Lectures/Cohort_03/FR_3rd_Cohort.md
